version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - brand-dashboard-net

  backend:
    build: ./backend
    container_name: brand-dashboard-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - brand-dashboard-net

  frontend:
    build: ./frontend
    container_name: brand-dashboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - brand-dashboard-net

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8090:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - brand-dashboard-net

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - trino
      - mongo
    environment:
      - SUPERSET_SECRET_KEY=your_super_secret_key_for_superset
      - SUPERSET_GUEST_TOKEN_JWT_SECRET=your-guest-token-secret-key-that-is-very-secret
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - PYTHONPATH=/app
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - superset-data:/var/lib/superset
    networks:
      - brand-dashboard-net

volumes:
  mongo-data:
  superset-data:

networks:
  brand-dashboard-net:
    driver: bridge
