version: '3.8'

x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - redash-postgres
    - redash-redis
  env_file: ./redash.env
  restart: always
  networks:
    - brand-dashboard-net

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - brand-dashboard-net

  backend:
    build: ./backend
    container_name: brand-dashboard-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - brand-dashboard-net

  frontend:
    build: ./frontend
    container_name: brand-dashboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - brand-dashboard-net

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8090:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - brand-dashboard-net

  redash-server:
    <<: *redash-service
    container_name: redash-server
    command: server
    ports:
      - "5001:5000"
    environment:
      - REDASH_WEB_WORKERS=4
      - REDASH_FRAME_ANCESTORS="'self' http://localhost:3000 http://localhost:8080 http://127.0.0.1:3000 http://127.0.0.1:8080"
      - REDASH_ALLOW_IFRAME_EMBEDDING=true
      - REDASH_DISABLE_FRAME_ANCESTORS=true
    depends_on:
      - redash-postgres
      - redash-redis

  redash-worker:
    <<: *redash-service
    container_name: redash-worker
    command: worker
    environment:
      - QUEUES=queries,default
      - WORKERS_COUNT=2
    depends_on:
      - redash-server

  redash-postgres:
    image: postgres:13-alpine
    container_name: redash-postgres
    env_file: ./redash.env
    volumes:
      - redash-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - brand-dashboard-net

  redash-redis:
    image: redis:6-alpine
    container_name: redash-redis
    restart: unless-stopped
    networks:
      - brand-dashboard-net

volumes:
  mongo-data:
  redash-postgres-data:

networks:
  brand-dashboard-net:
    driver: bridge
